---
inventory:
  plugin: NetBoxInventory2
  options:
    defaults_file: "defaults.yaml"
    nb_url: http://netbox.example.com
    nb_token: ""
    use_platform_slug: true
    filter_parameters:
      status: "active"
      role: "router"
      #name: ["switch01", "switch02"]


runner:
  plugin: threaded
  options:
    num_workers: 20

logging:
  to_console: false
